languageCode = "it"
languageName = "Italiano"
weight = 2
title = "Gnammyfy"

[params]
  displayName = "Italiano"
  isoCode = "it"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/blowfish_logo_transparent.png"
  description = "in cucina con una fuorisede"

[params.author]
  name = "GNAMMYFY"
  image = "img/blowfish_logo.png"
  headline = "in cucina con una fuorisede"
  bio = "in cucina con una fuorisede"
  links = [
    { x-twitter = "https://twitter.com/burufugu" },
    { github = "https://github.com/nunocoracao/blowfish" },
  ]