languageCode = "en"
languageName = "English"
weight = 1
title = "Ilaria La Torre"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/blowfish_logo_transparent.png"
  description = "My personal portfolio"

[params.author]
  name = "Ilaria La Torre"
  email = "ilarialatorre01@gmail.com"
  image = "img/blowfish_logo.png"
  headline = "My personal portfolio"
  bio = "My personal portfolio"
  links = [
    { x-twitter = "https://twitter.com/burufugu" },
    { github = "https://github.com/nunocoracao/blowfish" },
  ]