languageCode = "it"
languageName = "Italiano"
weight = 2
title = "Ilaria La Torre"

[params]
  displayName = "Italiano"
  isoCode = "it"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/blowfish_logo_transparent.png"
  description = "Il mio portfolio personale"

[params.author]
  name = "Ilaria La Torre"
  image = "img/blowfish_logo.png"
  headline = "Il mio portfolio personale"
  bio = "Il mio portfolio personale"
  links = [
    { x-twitter = "https://twitter.com/burufugu" },
    { github = "https://github.com/nunocoracao/blowfish" },
  ]