languageCode = "it"
languageName = "Italiano"
weight = 5
title = ""

[params]
  displayName = "Italiano"
  isoCode = "it"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/blowfish_logo_transparent.png"
  description = "in cucina con una fuorisede"

[params.author]
  name = "GNAMMYFY"
  image = "img/blowfish_logo.png"
  email = "ilarialatorre01@gmail.com"
  headline = "in cucina con una fuorisede v.2"
  bio = "in cucina con una fuorised v.2 "
  links = [
   { instagram = "https://instagram.com/ilarialatorree" },
    { tiktok = "https://wwww.tiktok.com/@ilarja._" },
  ]