[[main]]
  name = "Home"
  weight = 10

[[main]]
  name = "Merch"
  pageRef = "users"
  weight = 60

[[main]]
  name = "Chi sono"
  url = "https://www.teepublic.com/user/blowfish-store/t-shirts"
  weight = 80
  
#[[main]]
#  name = "Test"
#  pageRef = "pagTest"
#  weight = 1000

[[main]]
  identifier = "instagram"
  pre = "instagram"
  url = "https://instagram.com/ilarialatorree"
  weight = 200

#[[main]]
#  identifier = "mastodon"
#  pre = "mastodon"
#  weight = 300
#  url = "https://masto.ai/@blowfish"

[[main]]
  identifier = "tiktok"
  pre = "tiktok"
  url = "https://wwww.tiktok.com/@ilarja._"
  weight = 400


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

 [[footer]]
   name = "Tags"
   pageRef = "tags"
   weight = 10

 [[footer]]
   name = "Authors"
   pageRef = "authors"
   weight = 20
